In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(torch.__version__)

2.8.0+cu126


In [2]:
# scalar

scalar = torch.tensor(7)

In [3]:
MATRIX = torch.tensor([[1,2],
                      [3,4]])

In [4]:
torch.rand(1,1)

tensor([[0.4309]])

In [5]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones.dtype

torch.float32

In [9]:
identity = torch.eye(3,4)
identity

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

### Creating a range of tensors and tensors -like

In [10]:
#use rotch.arange()
rangee = torch.arange(0,10)

In [11]:
range_to_zeros = torch.zeros_like(input=rangee)
range_to_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False,)
float_16_tensor = float_32_tensor.type(torch.float16)

In [13]:
np_array = np.random.rand(3,4,4)
np_array = np_array.astype(np.float32)

In [14]:
tensor_from_np = torch.from_numpy(np_array)
#tensor_from_np_gpu = tensor_from_np.to('cuda')
#back to cpu
#tensor_from_np_cpu = tensor_from_np_gpu.to('cpu')
#tensor_from_np_cpu

In [15]:
# find out more about tensor
print(tensor_from_np)
print(f"Datatype of tensor : {tensor_from_np.dtype}")
print(f"Shape of tensor: {tensor_from_np.shape}")
print(f"Deviace tensor is on: {tensor_from_np.device}")

tensor([[[0.6750, 0.8498, 0.3303, 0.0557],
         [0.3089, 0.7541, 0.9471, 0.6115],
         [0.9092, 0.8488, 0.8752, 0.1703],
         [0.7782, 0.8015, 0.2719, 0.4281]],

        [[0.0560, 0.9014, 0.5921, 0.2752],
         [0.2396, 0.6072, 0.6942, 0.2557],
         [0.1903, 0.8163, 0.2087, 0.8351],
         [0.6672, 0.4506, 0.1626, 0.8832]],

        [[0.1375, 0.1817, 0.0626, 0.2356],
         [0.8249, 0.4104, 0.3399, 0.2161],
         [0.6139, 0.1713, 0.9820, 0.5027],
         [0.4726, 0.2233, 0.3422, 0.3988]]])
Datatype of tensor : torch.float32
Shape of tensor: torch.Size([3, 4, 4])
Deviace tensor is on: cpu


In [16]:
tensor1 = torch.rand(3,2)
tensor2 = torch.rand(3,2)
result1  = tensor1.mm(tensor2.T) #.mm() and matmul() as matrix multiplication as using @
result1

tensor([[0.2624, 0.6923, 0.4512],
        [0.2658, 0.7652, 0.5386],
        [0.1815, 0.6019, 0.4690]])

In [17]:
## Tensor aggr
tensor = torch.arange(0, 100, 10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
%%time
torch.min(tensor), torch.max(tensor), torch.mean(tensor.to(torch.float32)), torch.sum(tensor)

CPU times: user 270 µs, sys: 909 µs, total: 1.18 ms
Wall time: 2.48 ms


(tensor(0), tensor(90), tensor(45.), tensor(450))

In [19]:
#argmin, argmax = positinal = returns index of min or max value
torch.argmin(tensor), torch.argmax(tensor)

(tensor(0), tensor(9))

# reshaping, stacking, squeezing and unsqueezing
* Reshaping an input tensor to a defined shape
* View - Return a view of an input tensor of certain sha[pe but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (Ovstack) or side by side (hstack)
* Squeeze - removes all 1 dim from a tensor
* Unsqueeze - add a 1 dim to a target tensor
* Permute - return a view of the input with dim permuted(swapped) in a certain way

In [20]:
# reshaping, stacking, squeezing and unsqueezing

x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [21]:
# Add extra dim
x_reshaped = x.reshape(2,5 )
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [22]:
#CHange the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [23]:
# Stack tensors
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [24]:
# .squeeze and usqueeze
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])
torch.Size([2, 2, 2])


In [25]:
### torch.permute is a PyTorch function used to reorder
x = torch.randn(10, 3, 64, 64) # Example tensor with shape (batch_size, channels, height, width)
print("Original shape:", x.shape)

# Permute dimensions to (batch_size, height, width, channels)
y = torch.permute(x, (0, 2, 3, 1))
print("Permuted shape:", y.shape)

Original shape: torch.Size([10, 3, 64, 64])
Permuted shape: torch.Size([10, 64, 64, 3])


# Indexing data in tensors

In [26]:
x = torch.arange(1,10).reshape(1,3,3)

In [27]:
x[0,:,2]

tensor([3, 6, 9])

#Reproducbility(trying to take random out of random)


In [28]:
t_A = torch.rand(3,4)
t_B = torch.rand(3,4)
print(t_A == t_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [29]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
t_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
t_D = torch.rand(3,4)

print(t_C)
print(t_D)
print(t_C == t_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Running tensors and torch objects

In [30]:
#Running tensors and torch objects
!nvidia-smi

Thu Oct  9 08:28:55 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [31]:
#check if there is gpu on pc
import torch
torch.cuda.is_available()

True

In [32]:
#setup gpu mode
device = "cuda" if torch.cuda.is_available() else "cpu"


In [33]:
#count number of diveces
torch.cuda.device_count()

1

In [34]:
"""import argparse
import torch

parser = argparse.ArgumentParser(description='PyTorch Example')
parser.add_argument('--disable-cuda', action='store_true',
                    help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')"""

"import argparse\nimport torch\n\nparser = argparse.ArgumentParser(description='PyTorch Example')\nparser.add_argument('--disable-cuda', action='store_true',\n                    help='Disable CUDA')\nargs = parser.parse_args()\nargs.device = None\nif not args.disable_cuda and torch.cuda.is_available():\n    args.device = torch.device('cuda')\nelse:\n    args.device = torch.device('cpu')"

In [35]:
#putting a tensor to gpu
tensor = torch.tensor([1,2,3], device='cpu')
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [36]:
tensor_gpu = tensor.to(device)
tensor_gpu.device

device(type='cuda', index=0)

In [37]:
tensor_gpu_to_np = tensor_gpu.cpu().numpy()